quez = [
    "Type of work ability which is the study of user behavior that people like or dislike the new software.",
    "This is one of the Software Quality Metrics. As the name suggests, these metrics take the count of defects found in each sprint. This is a very simple yet useful metrics for assessing the quality of the user stories delivered during any sprint.",
    "This is one of the steps in developing a software system. With the help of this we can convert the shape structure in to a programming language. Every part of the design is a program module. ",
    "This is one of the Software Quality Metrics. Important metrics especially for mobile apps and online websites. It is a measure of how often the mobile app or website crashes in any environment. It is an indicator of the quality of the code. The better the code, the longer it will be able to sustain without crashing. ",
    "This is one of the best practices in writing codes. Tall and narrow columns are easy to be read and seem comfortable to the eyes.",
    "This is one of the Software Quality Metrics. As the name suggests, these metrics take the count of defects found in each sprint. This is a very simple yet metrics for assessing the quality of the user stories delivered during any sprint. ", 
    "This is one of the steps in developing a software system. It is a study of following factors which plays a major role in this step.",
    "This is one of the Software Quality Metrics. The first measure of the quality of any products is the number of defects found and fixed. Though there a many \"conditions apply\" cases this is the first ballpark estimate of the quality of the software.",
    "This is one of the steps in developing a software system. This step is required after that when customer use our software and getting some problems.",
    "This is one of the Software Quality Metrics. It is defined as the time it takes from the time of project or sprint kick-off to the completion. In an agile process, we normally pick up user stories that will be delivered at the end of the sprint.",
    "This is one of the steps in developing a software system. It means providing the information on client site. ",
    "This is one of the best practices in writing codes. This is done to enhance the readability of the code without modifying the basic functionality of the code.",
    "This is one of the steps in developing a software system, In this step with the help of this knowledge we find out the errors at the present time software system which is needed to change for improvement. ",
    "Type of work ability which determine that the new software is under the government rule or not.",
    "Type of work ability where the new system will be more suitable for the user or not is checked by the expert",
    "This is one of the best practices in writing codes. It is up to the coders which type of programming style to choose.",
    "This is one of the best practices in writing codes. It is better to group the tasks in different blocks/functions of code separating them with proper space. You can add a comment at the starting of every block.",
    "This is one of the best practices in writing codes. While following the standards, take care that you do not comment unnecessarily. Too much explanation will make your code look clumbsy.", 
    "This is one of the steps in developing a software system. During the process of this step need specification converted in to a base, which is used in programming language.",
    "________ is a part of science in which several kind of method, thoughts and techniques used for getting the high quality software and computer programs.",
    "We can judge the ___________ of software Engineering with the importance of its attributes.",
    "We can judge the usefulness of the software Engineering with the ________ of its attributes.",
    "We can judge the usefulness of the software Engineering with the importance of its _________.",
    "The basic target of software Engineering is to provide the _____________, which can be delivered.",
    "The basic target of software Engineering is to provide the high quality software, which can be _________",
    "Thus we can say that this is the best way or programs to get the following points: 1. To provide the best _______ of software system",
    "Thus we can say that this is the best way or programs to get the following points: 2. To make _________ the software systems and develop them",
    "Thus we can say that this is the best way or programs to get the following points: 3. To improve the _____________",
    "Thus we can say that this is the best way or programs to get the following points: 4. To maintain the _______ of development of Software system",
    "Thus we can say that this is the best way or programs to get the following points: 5. Job __________ of software engineering",
    "To achieve consistency, software development process is divided into set of ______",
    "To achieve _________, software development process is divided into set of phases",
    "Steps used to develop a software system: 1. ___________",
    "Steps used to develop a software system: 2. ___________",
    "Steps used to develop a software system: 3. ___________",
    "Steps used to develop a software system: 4. ___________",
    "Steps used to develop a software system: 5. ___________",
    "Steps used to develop a software system: 6. ___________",
    "Steps used to develop a software system: 7. ___________",
    "Steps used to develop a software system: 8. ___________",
    "In this step, we get more knowledge from everywhere on computer and manually",
    "In this step, we think about the present system and future system and compared them. The area of comparison is skilled manpower, estimated time period, and other important things.",
    "Do we have the required technology? With the available tools can we developed the new system? Can the future system provide the result as required?",
    "This factor is determined that new software benefits and savings is more in the comparison of old software.",
    "Determined that the new software is under the govt. rule or not",
    "During this process several kind of tools and method used .flow chart, collected data, diagram and etc. are the part of this exercise. After the resolution of all problems and needs regarding this, information is organized into a ____________.",
    "Takes place after analysis of structured.",
    "In this design many kind of object raised in the domain of problem and relationship between these objects is figured out.",
    "Every part of the design is a _____________",
    "In this phase as a whole system all modules which are tested jointly according to architectural design.",
    "For getting the information that interconnection concerned to modules are correct or not this step taken by the developer. ",
    "We have three types of implementation. 1. ________ ",
    "We have three types of implementation. 2. ________ ",
    "We have three types of implementation. 3. ________ ",
    "During the process of software development corrective fault not found or discovered",
    "Under this step functions which are performed by this software increased according to the need of customer",
    "Transform the software to new opearting system, environments or to a new computer",
    "SDLC means?",
    "This is the first step where user initiates the request for a desired software product. He contacts the service provider and tries to negotiate the terms. He submits his request to the service providing organization in writing.",
    "This step onwards the software development team works to carry on the project. The team holds discussions with various stakeholders from problem domain and tries to bring out as much information as possible on their requirements.",
    "The requirements are contemplated and segregated into _______ requirements, system requirements and functional requirements",
    "The requirements are contemplated and segregated into user requirements, _______ requirements and functional requirements",
    "The requirements are contemplated and segregated into user requirements, system requirements and _______ requirements",
    "After requirement gathering, the team comes up with a rough plan of software process. At this step the team analyzes if a software can be made to fulfill all requirements of the user and if tehre is any possiblity of software being no more useful.",
    "At this step the developers decide a roadmap of their plan and try to bring up the best software suitable for the project.",
    "Includes understanding of software product limitations, learning system related problems or changes to be done in existing systems beforehand, identifying and adressing the impact of project on organization and personnel etc.",
    "Next step is to bring down whole knowledge of requirements and analysis on the desk and design the software product.",
    "Also known as programming phase. The implementation of software design starts in terms of writing program code in the suitable programming language and developing error-free executable programs efficiently.",
    "An estimate that says that 50 percent of whole software development process should be tested",
    "Software may need to be integrated with the libraries, databases and other program(s). This stage of SDLC is involved in the integration of software with outer world entities.",
    "This means installing the software on user machines. At times, software needs post-installation configurations at user end. Software is tested for portability and adaptability and integration related issues are solved during this.",
    "This phase confirms the software operation in terms of more efficiency and less errors.",
    "This phase may face challenges from hidden bugs and real-world unidentified problems.",
    "As time elapses, the software may decline on the performance front. It may go completely obsolete or may need intense upgradation. Hence a pressing need to eliminate a major portion of the system arises.",
    "This phase includes archiving data and required software components, planning disposition activivity and terminating system at appropriate end-of-system time.",
    "The _______ helps developer to select a strategy to develop the software",
    "The software development paradigm helps developer to select a ______ to develop the software.",
    "_________ is the simplest model of software development paradigm.",
    "It says all the phases of SDLC will function one after another in linear manner. That is, when the first phase is finished then only the second phase will start and so on. ",
    "Provides a series of steps to be followed to design and develop a software product efficiently",
    "Parts of SDLC: 1. _______ ",
    "Parts of SDLC: 2. _______ ",
    "Parts of SDLC: 3. _______ ",
    "Parts of SDLC: 4. _______ ",
    "Parts of SDLC: 5. _______ ",
    "Parts of SDLC: 6. _______ ",
    "Parts of SDLC: 7. _______ ",
    "Parts of SDLC: 8. _______ ",
    "Parts of SDLC: 9. _______ ",
    "Parts of SDLC: 10. _______ ",
    "Parts of SDLC: 11. _______ ",
    "Parts of Waterfall Model: 1. ______",
    "Parts of Waterfall Model: 2. ______",
    "Parts of Waterfall Model: 3. ______",
    "Parts of Waterfall Model: 4. ______",
    "Parts of Waterfall Model: 5. ______",
    "Parts of Waterfall Model: 6. ______",
    "This model assumes that everything is carried out and taken place perfectly as planned in the previous stage and there is no need to think about the past issues that may arise in the next phase.",
    "This model does not work smoothly if there are some issues left at the previous step.",
    "The sequential nature of model does not allow us to go back and undo or redo our actions",
    "This model is best suited when developers already have designed and developed similar software in the past and are aware of all its domains.",
    "This model leads the software development process in iterations. It projects the process of development in cyclic manner repeating every step after every cycle of SDLC process.",
    "The software is first developed on very small scale and all the steps are followed which are taken into consideration. Then, on every next iteration, more features and modules are designed, coded, tested and added to the software. Every cycle produces a software, which is complete in itself and has more features and capabilities than that of the previous one.",
    "After each iteration, the management team can do work on risk management and prepare for the next iteration. Because a cycle includes small portion of whole software process, it is easier to manage the development process but it consumes more resources.",
    "_____ is a combination of both, iterative model and one of the SDLC model. It can be seen as if you choose one SDLC model and combine it with cyclic process (iterative model).",
    "This model considers risk, which often goes un-noticed by most other models. The model starts with determining objectives and constraints of the software at the start of one iteration. Next phase is of prototyping the software. This includes risk analysis. Then one standard SDLC model is used to build the software. In the fourth phase of the plan of next iteration is prepared.",
    "provides means of testing of software at each stage in reverse manner.",
    "At every stage, test plans and test cases are created to verify and validate the product according to the requirement of that stage. For example, in requirement gathering stage the test team prepares all the test cases in correspondence to the requirements. Later, when the product is developed and is ready for testing, test cases of this stage verify the software against its validity towards requirements at this stage.",
    " This model is also known as verification and validation model.",
    "Both _______ and validation go in parallel",
    "Both verification and _______ go in parallel",
    "This model is the simplest model in its form. It requires little planning, lots of programming and lots of funds. This model is conceptualized around the big bang of universe. As scientists say that after big bang lots of galaxies, planets and stars evolved just as an event. Likewise, if we put together lots of programming and funds, you may achieve the best software product.",
    "For this model, very small amount of planning is required. It does not follow any process, or at times the customer is not sure about the requirements and future needs. So the input requirements are arbitrary.",
    " It does not follow any process, or at times the customer is not sure about the requirements and future needs.",
    "For the Big Bang Model, input requirements are _______",
    "This model is not suitable for large software projects but good one for learning and experimenting.",
    "People often fail to understand that _____ has minimal value if there is no quality.",
    "The _________ can be defined as the ability of the software to function as per user requirement. ",
    "The quality of software can be defined as the ability of the software to function as per ___________ . ",
    "It is always important to have a good and aesthetic design to please users",
    "Be it any software it should be able to perform the functionality impeccably without issues",
    "Be it any software it should be able to perform the functionality ___________ without issues",
    "Be it any software it should be able to perform the ___________ impeccably without issues",
    "means the ability of the software to work without any issue for a long period of time.",
    "Software should be able to perform consistently over platform and devices",
    "Bugs associated with any software should be able to capture and fix quickly and news tasks and enhancement must be added without any trouble",
    "customer and companies who make this app should feel that the money spent on this app has not fone to waste."
    "was first introduced in the US Airforce in the year 1977.  The main intention of this model was to maintain harmony between users and developers.",
    "was introduced in the year 1978. It was a kind of hierarchical model that\'s structured around high-level characteristics.  ",
    "It was a kind of hierarchical model that\'s structured around high-level characteristics.",
    "measures software quality on the basis of certain characteristics.",
    "mainly focussed on the attributes and sub-attributes to connect properties of the software to the quality attributes",
    "Have a clear idea about how the quality assurance process will be carried out through the project. Quality engineering activities required should also be set at the beginning along with team skill check.",
    " Checkpoints at required intervals should be set",
    "pointers or numbers which help you understand the attributes of a product,",
    "Three Ps?",
    "are an indicator of the health of the product, process, and project.",
    "Parts of metrics: 1. _________",
    "Parts of metrics: 2. _________",
    "As the name suggests it is the average time between two failures in a system. Based on the AUT and expectation of business the definition of failure may vary.",
    " basically the time it takes for the developers to find a critical issue with the system, fix it and push the fix patch to production",
    " is similar to the lead time with a difference that leads time is measured per user story, while cycle time is measured per task. For eg, if database creation is part of the user story related to client data.",
    "These metrics are in line with the agile principle of dynamic, fast and quality delivery. It is an indicator of the number of test cases that pass in the first run itself.",
    "They are a series of procedures that can be defined for a particular programming language specifying a programming style, the methods, & different procedures. ",
    "makes sure that all the developers working on the project are following certain specified guidelines. The code can be easily understood and proper consistency is maintained.",
    "has a positive impact on the quality of the program and one should maintain it while coding",
    " Software becomes vulnerable to attacks if it is inconsistent, contains bugs and errors in logic. Most of the aforementioned problems arise due to the faulty programming code that might have resulted from poor coding practices.",
    "Poor coding has an adverse effect on the performance of the site. ",
    "Try to define different sections of the code by segmenting blocks of code into a __________ ",
    "Make use of _________ for indicating the start and end of the control structures along with a clear specification of where the code is between them",
    "It is a good practice to comment while writing code. It helps other developers to understand your code. ",
    "There is no particular style defined, but any style can be chosen for writing code.",
    "This can be used for naming where the first letter of each word is capitalized except for the first word.",
    "Name your function using an underscore between the words.",
    "also known as DIE (duplication is evil)",
    "DRY means?",
    " It is a good practice to write your own code and dont copy. It is a known fact that most software programs aim at automating repetitive tasks. Therefore, the code of the application should be such that the same code is not repeated over and over again.",
    " Too many nesting structures make it difficult to understand the code.",
    "It is possible to write the whole code in a single file but there could be problems related to its readability and maintenance. ",
    "While working on open source projects, multiple developers give input in a single software. Therefore, it is good to maintain code readability, so that the team can work on it in an easy manner. It is also advantageous to go through the source code of these projects to get an idea about what the developers are doing.",

]
answers = [
    "Social Work Ability",
    "Defect Count Per Sprint",
    "Coding and Module Testing",
    "Application Crash Rate",
    "Use short line length",
    "Defect Count Per Sprint",
    "Software Need Analysis and Specification",
    "Defect Density",
    "System Maintenance",
    "Lead Time",
    "System Implementation",
    "Refactoring Code",
    "Statement of Problem and System Study",
    "Legal Work Ability",
    "Technical Work Ability",
    "OOPs vs. Procedural Programming",
    "Grouping Code",
    "Avoid Commenting on Obvious Things",
    "Software Design and Specification",
    "Software Engineering",
    "usefulness",
    "importance", 
    "attributes",
    "high quality software",
    "delivered",
    "output",
    "easy to use",
    "rate of production",
    "budget",
    "satisfaction",
    "phases",
    "consistency",
    "Statement of problem and system study",
    "Study of work ability",
    "Software need analysis and specification",
    "Software design and specification",
    "Coding and module testing",
    "Integration and system testing",
    "System implementation",
    "System maintenance",
    "Statement of problem and system study",
    "Study of work ability", 
    "Technical Work Ability",
    "Economic Work Ability",
    "Legal Work Ability",
    "Software need specification document",
    "Architecture design",
    "Object oriented design",
    "program module",
    "Integration and system testing",
    "Integration and system testing",
    "Direct conversion",
    "Phased conversion",
    "Parallel conversion",
    "Corrective maintenance",
    "Perfective maintenance",
    "Adaptive maintenance",
    "Software Development Life Cycle",
    "Communication",
    "Requirement Gathering",
    "user",
    "system",
    "functional",
    "feasiblity study",
    "system analysis",
    "system analysis",
    "Software Design",
    "Coding",
    "Testing",
    "Integration",
    "Implementation",
    "Operation and Maintenance",
    "Disposition",
    "Disposition", 
    "Disposition",
    "Software Development Paradigm",
    "Strategy",
    "Waterfall model",
    "Waterfall model", 
    "Software Development Life Cycle", 
    "Communication",
    "Requirement Gathering",
    "Feasibility Study",
    "System Analysis", 
    "Software Design",
    "Coding",
    "Testing",
    "Integration",
    "Implementation",
    "Operations and Maintenance",
    "Disposition",
    "Requirement Gathering",
    "System Analysis",
    "Coding",
    "Testing",
    "Implementation",
    "Operations and Maintenance",
    "Waterfall model",
    "Waterfall model",
    "Waterfall model",
    "Waterfall model",
    "Iterative model",
    "Iterative model",
    "Iterative model",
    "Spiral model",
    "Spiral model",
    "V-Model",
    "V-Model",
    "V-Model",
    "Verification",
    "Validation",
    "Big Bang Model",
    "Big Bang Model",
    "Big Bang Model",
    "Arbitrary",
    "Big Bang Model",
    "Speed",
    "Quality of software",
    "User Requirement",
    "Good design",
    "Reliability",
    "Impeccably",
    "functionality",
    "durability",
    "Consistency",
    "Maintainability",
    "Value for money",
    "Mc call\'s Model",
    "Boehm Quality model",
    "Boehm Quality Model",
    "Dromey's Quality Model",
    "Management plan",
    "Proper checkpoints",
    "Metrics",
    "Product Process Project",
    "Software Quality Metrics",
    "Data Accuracy",
    "Metrics Selection",
    "Meantime Between Failures",
    "Meantime to Recover",
    "Cycle Time",
    "First Time Pass Rate",
    "Coding Standards",
    "Coding Standards",
    "Consistency",
    "Security Concerns",
    "Performance Issues",
    "Paragraph",
    "Indentation",
    "Code Comments and Proper Documentation ",
    "Use of Indentation",
    "CamelCase",
    "UnderScore",
    "Principle of DRY",
    "Don't Repeat Yourself",
    "Principle of DRY",
    "Deep nesting structure should be avoided",
    "Proper organization of files and folder",
    "Open source code readability",
]

quez2 = [
    "the ongoing effort to protect these networked systems and all of the data from unauthorized use or harm.",
    "the person who your friends and family interact with on a daily basis at home, at school, or work.",
    "who you are in cyberspace, how you present yourself to others online.",
    "any information about you is called?",
    "Records like Electronic Health Records, physical health, mental health etc.",
    "information about your grades and test scores, your attendance, courses taken, awards and degrees rewarded, and any disciplinary reports",
    "may include information about your income and expenditures.",
    "What gives thieves access to your accounts?",
    "What do criminals steal for short-term gain?",
    "What do criminals steal for long-term gain?",
    "includes personnel information, intellectual properties, and financial data.",
    "includes application materials, payroll, offer letters, employee agreements, and any information used in making employment decisions.",
    "such as patents, trademarks and new product plans, allows a business to gain economic advantage over its competitors",
    "can be considered a trade secret; losing this information can be disastrous for the future of the company.",
    "allows a business to gain economic advantage over its competitors",
    "such as income statements, balance sheets, and cash flow statements of a company",
    "gives insight into the health of the company.",
    "Types of Organizational Data: 1. __________",
    "Types of Organizational Data: 2. __________",
    "IoT means?",
    "is a large network of physical objects, such as sensors and equipment that extend beyond the traditional computer network.",
    "This data has created a new area of interest in technology and business called?",
    "CIA triad? C is what?",
    "CIA triad? I is what?",
    "CIA triad? A is what?",
    "ensures the privacy of data by restricting access through authentication encryption.",
    "Confidentiality ensures the privacy of data by restricting access through what?",
    " assures that the information is accurate and trustworthy.",
    "ensures that the information is accessible to authorized people.",
    "What is another term for confidentiality?",
    "is accuracy, consistency, and trustworthiness of the data during its entire life cycle. ",
    "Data must be unaltered during transit and not changed by unauthorized entities. ",
    " Company policies should restrict access to the information to authorized personnel and ensure that only those authorized individuals view this data.",
    "The data may be compartmentalized according to the security or sensitivity level of the information. ",
    "Methods to ensure _______ include data encryption, username ID and password, two factor authentication, and minimizing exposure of sensitive information.",
    " File permissions and user access control can prevent unauthorized access. ",
    "It can be used to prevent accidental changes by authorized users.",
    "It must be available to restore any corrupted data",
    "can be used to verify integrity of the data during transfer.",
    "is used to verify the integrity of files, or strings of characters, after they have been transferred from one device to another across your local network or the Internet.",
    "are calculated with hash functions.",
    "uses a mathematical algorithm to transform the data into fixed-length value that represents the data",
    "Maintaining equipment, performing hardware repairs, keeping operating systems and software up to date, and creating backups ensure the ________ of the network and data to the authorized users.",
    "occurs when an attacker attempts to overwhelm resources so the services are not available to the users.",
    "What was the name of the online password manager that detected unusual activity on its network in July 2015?",
    "The high tech toy maker for children, ________ , suffered a security breach to its database in November 2015. ",
    "In the Vtech incident what had become a new target for hackers?",
    "(Vtech) The information was not secured properly, and the company website did not support secure ________________.",
    "(Vtech)  The passwords in the database were scrambled using ____________",
    "(Vtech) but the security questions and answers were stored in ___________.",
    "____________ is one of the nationwide consumer credit reporting agencies in the United States.",
    "(Equifax Inc.) The attackers exploited a vulnerability in the __________ web application software.",
    "are individuals or groups who attempt to exploit vulnerability for personal or financial gain.",
    "are interested in everything, from credit cards to product designs and anything with value.",
    "These people are sometimes called Script Kiddies",
    "They are usually attackers with little or no skill, often using existing tools or instructions found on the Internet to launch attacks. ",
    "Some of them are just curious, while others are trying to demonstrate their skills and cause harm. ",
    "They may be using basic tools, but the results can still be devastating.",
    "This group of attackers break into computers or networks to gain access.",
    "break into networks or computer systems to discover weaknesses so that the security of these systems can be improved. ",
    "take advantage of any vulnerability for illegal personal, financial or political gain.",
    "are somewhere between white and black hat attackers. ",
    "may report the vulnerability to the owners of the system if that action coincides with their agenda.",
    "These hackers publish the facts about the vulnerability on the Internet so that other attackers can exploit it.",
    "These hackers include organizations of cyber criminals, hacktivists, terrorists, and state-sponsored hackers.",
    "are usually groups of professional criminals focused on control, power, and wealth.",
    "make political statements to create awareness to issues that are important to them.",
    "gather intelligence or commit sabotage on behalf of their government.",
    "These attackers are usually highly trained and well-funded",
    "Their attacks are focused on specific goals that are beneficial to their government",
    "also have the potential to cause greater damage than external threats",
    "who use their programming skills for good, ethical and legal purposes.",
    "may perform network penetration tests in an attempt to compromise networks and systems by using their knowledge of computer security systems to discover network vulnerabilities",
    "individuals who commit crimes and do arguably unethical things, but not for personal gain or to cause damage.",
    "An example would be someone who compromises a network without permission and then discloses the vulnerability publicly.",
    "another important dimension of warfare, where nations can carry out conflicts without the clashes of traditional troops and machines. ",
    "an Internet-based conflict that involves the penetration of computer systems and networks of other nations.",
    "malware that was designed to damage Iran\'s nuclear enrichment plant.",
    "This malware did not hijack targeted computers to steal information.",
    " It was designed to damage physical equipment that was controlled by computers.",
    "It used modular coding that was programmed to perform a specific task within the malware.",
    " It used stolen digital certificates so the attack appeared legitimate to the system",
    "The purpose of this is to gain advantage over adversaries, whether they are nations or competitors",
    "any kind of software or hardware defect",
    "is the term used to describe a program written to take advantage of a known vulnerability.",
    "The act of using an exploit against a vulnerability",
    "are usually introduced by errors in the operating system or application code",
    "The major vulnerability discovered in Cisco IOS",
    " This vulnerability allowed attackers to gain control of enterprise-grade routers, such as the legacy Cisco 1841, 2811, and 3825 routers.",
    "This vulnerability was introduced into the system when an altered IOS version was installed in the routers",
    "Google formed a permanent team dedicated to finding software vulnerabilities.",
    " are often introduced by hardware design flaws.",
    "What exploit allows data to be retrieved from nearby address memory cells, even if the cells are protected. ",
    "What exploit repeatedly  rewrites memory in the same addresses",
    "What exploit was based on the discovery that due to proximity, constant changes applied to one of these capacitors could influence neighbor capacitors ",
    "are specific to device models and are not generally exploited through random compromising attempts.",
    "hardware exploits are more common in highly targeted attacks, T or F?"
    "traditional malware protection and a physical security are sufficient protection for the everyday user",
    "This vulnerability occurs when data is written beyond the limits of a buffer.",
    "are memory areas allocated to an application.",
    " By changing data beyond the boundaries of a buffer, the application accesses memory allocated to other processes. This can lead to a system crash, data compromise, or provide escalation of privileges.",
    "This data coming into the program could have malicious content, designed to force the program to behave in an unintended way.",
    "The maliciously crafted dimensions could force the program to allocate buffers of incorrect and unexpected sizes.",
    "This vulnerability is when the output of an event depends on ordered or timed outputs.",
    "becomes a source of vulnerability when the required ordered or timed events do not occur in the correct order or proper timing.",
    " Systems and sensitive data can be protected through techniques such as authentication, authorization, and encryption.",
    "Developers should not attempt to create their own security algorithms because it will likely introduce vulnerabilities.",
    " is the process of controlling who does what and ranges from managing physical access to equipment to dictating who has access to a resource, such as a file, and what they can do with it, such as read or change the file. ",
    "Nearly all access controls and security practices can be overcome if the attacker has physical access to target equipment.",
    "Incorrectly regulating who does what and what they can do with resources.",
    "When a malicious application accesses memory allocated to other processes.",
    "Malware is _____ Software",
    "Malware is Malicious ______",
    "is any code that can be used to steal data, bypass access controls, or cause harm to, or compromise a system.",
    "This malware is design to track and spy on the user.",
    "often includes activity trackers, keystroke collection, and data capture. ",
    "In an attempt to overcome security measures, spyware often modifies security settings.",
    "Spyware often bundles itself with legitimate software or with Trojan horses.",
    "is often installed with some versions of software. ",
    "Some adware is designed to only deliver advertisements but it is also common for adware to come with spyware.",
    "is malware designed to automatically perform action, usually online.",
    "Several computers are infected with bots which are programmed to quietly wait for commands provided by the attacker.",
    "This malware is designed to hold a computer system or the data it contains captive until a payment is made. ",
    "usually works by encrypting data in the computer with a key unknown to the user. ",
    "is spread by a downloaded file or some software vulnerability.",
    "This is a type of malware designed to persuade the user to take a specific action based on fear.",
    "forges pop-up windows that resemble operating system dialogue windows. ",
    " In reality, no problems were assessed or detected and if the user agrees and clears the mentioned program to execute, his or her system will be infected with malware.",
    " is designed to modify the operating system to create a backdoor.",
    "Most of this take advantage of software vulnerabilities to perform privilege escalation and modify system files.",
    " It is also common for these to modify system forensics and monitoring tools, making them very hard to detect. ",
    " Often, a computer infected by a rootkit must be wiped and reinstalled.",
    "is malicious executable code that is attached to other executable files, often legitimate programs. ",
    "Most of these require end-user activation and can activate at a specific time or date.",
    "These can also be programmed to mutate to avoid detection. ",
    "is malware that carries out malicious operations under the guise of a desired operation.",
    "This malicious code exploits the privileges of the user that runs it.",
    "This differs from a virus because it binds itself to non-executable files."
    "are malicious code that replicate themselves by independently exploiting vulnerabilities in networks. ",
    "usually slow down networks.",
    "Whereas a virus requires a host program to run, _____ can run by themselves.",
    "Other than the initial infection, they no longer require user participation.",
    "in 2001 the _________ worm had infected 658 servers.",
    "allows the attacker to take control over a device without the user\'s knowledge.",
    " are widely used to steal financial information.",
    "is a type of attack used to take control over a mobile device",
    "When infected, the mobile device can be instructed to exfiltrate user-sensitive information and send it to the attackers.",
    " example of an exploit with MitMo capabilities, allows attackers quietly to capture 2-step verification SMS messages sent to users.",
    " is an access attack that attempts to manipulate individuals into performing actions or divulging confidential information. ",
    " often rely on people\'s willingness to be helpful but also prey on people\'s weaknesses. ",
    "This is when an attacker calls an individual and lies to them in an attempt to gain access to privileged data.",
    "An example involves an attacker who pretends to need personal or financial data in order to confirm the identity of the recipient.",
    "This is when an attacker quickly follows an authorized person into a secure location.",
    "Another term for something for something",
    "Quid pro quo means?",
    "This is when an attacker requests personal information from a party in exchange for something, like a free gift.",
    "is the process of discovering the password used to protect a wireless network. ",
    "The attacker manipulates a person who knows the password into providing it.",
    "The attacker tries several possible passwords in an attempt to guess the password. ",
    "By listening and capturing packets sent on the network, an attacker may be able to discover the password if the password is being sent unencrypted",
    " is when a malicious party sends a fraudulent email disguised as being from a legitimate, trusted source. ",
    " is a highly targeted phishing attack.",
    "emails are customized to a specific person.",
    "a public Internet database containing information about domain names and their registrants.",
    " a popular port scanner",
    "APT means?",
    "They consist of a multi-phase, long term, stealthy and advanced operation against a specific target",
    "The purpose of this is to deploy customized malware on one or multiple of the target's systems and remain undetected",
    "results in some sort of interruption of network service to users, devices, or applications.",
    "This is when a network, host, or application is sent an enormous quantity of data at a rate which it cannot handle",
    "This causes a slowdown in transmission or response, or a crash of a device or service.",
    "This is when a maliciously formatted packet is sent to a host or application and the receiver is unable to handle it. ",
    " For example, an attacker forwards packets containing errors that cannot be identified by the application, or forwards improperly formatted packets. This causes the receiving device to run very slowly or crash.",
    "are considered a major risk because they can easily interrupt communication and cause significant loss of time and money.",
    " These attacks are relatively simple to conduct, even by an unskilled attacker.",
    "is similar to a DoS attack but originates from multiple, coordinated sources",
    "What is a network of infected hosts?",
    "What are the infected hosts of a botnet called?",
    "What controls a zombie in a botnet?",
    "SEO means?",
    "is a set of techniques used to improve a website's ranking by a search engine.",
    " a malicious user could use SEO to make a malicious website appear higher in search results.",
    "The goal of this is to increase traffic to malicious sites that may host malware or perform social engineering.",
    "are attacks that use multiple techniques to compromise a target. ",
    "By using several different attack techniques at once, attackers have malware that are a hybrid of worms, Trojan horses, spyware, keyloggers, spam and phishing schemes.",
    "store your data and are the portal to your online life. ",
    "a web-based IoT device scanner.",
    "SSID means?",
    "This exploit takes advantage of This flaw allows an intruder to break the encryption between the wireless router and the wireless client, and allow the intruder to access and manipulate the network traffic.",
    "someone intercepting your information is also known as?",
    " is the process of converting the information into a form where an unauthorized party cannot read it. ",
    " The encryption itself does not prevent someone from intercepting the data.",
    "can only prevent an unauthorized person from viewing or accessing the content.",
    "is a Windows feature that can encrypt data.",
    "NAS means?",
    "AWS means?",
    "What program writes zeroes and ones to your files to erase data? (Windows)",
    "What program writes zeroes and ones to your files to erase data? (Linux)",
    "What program writes zeroes and ones to your files to erase data? (Mac OSX)",
    "PIN means?",
    " Examples are credit card, ATM card, phone, or fob",
    "fingerprint, palm print, as well as facial or voice recognition",
    "is an open standard protocol that allows an end user's credentials to access third party applications without exposing the user's password",
    "OAuth means?",
    "acts as the middle man to decide whether to allow end users access to third party applications. ",
    "Private browser name for Microsoft Internet Explorer?",
    "Private browser name for Google Chrome?",
    "Private browser name for Mozilla Firefox?",
    "Private browser name for Safari?",
    "SSL means?",
]

answers2 = [
    "Cybersecurity",
    "Offline Identity",
    "Online Identity",
    "Your Data",
    "Medical Records",
    "Education Records",
    "Employment and Financial Records",
    "Credentials",
    "Money",
    "Identity",
    "Corporate data",
    "Personnel Information",
    "Intellectual property",
    "Intellectual property",
    "Intellectual property",
    "Financial Data",
    "Financial Data",
    "Traditional Data",
    "Internet of Things and Big Data",
    "Internet of Things",
    "Internet of Things",
    "Big Data",
    "Confidentiality",
    "Integrity",
    "Availability",
    "Confidentiality",
    "Authentication Encryption",
    "Integrity",
    "Availability",
    "Privacy",
    "Integrity",
    "Integrity",
    "Confidentiality",
    "Confidentiality",
    "Confidentiality",
    "Integrity",
    "Version control",
    "Backups",
    "Checksum hashing",
    "Checksum",
    "Checksums",
    "Hash Function",
    "Availability",
    "Denial of Service",
    "LastPass",
    "Vtech",
    "Toy Tablet",
    "SSL communication",
    "MD5 hash function",
    "plaintext",
    "Equifax Inc.",
    "Apache Struts",
    "Attackers",
    "Attackers",
    "Amateurs",
    "Amateurs",
    "Amateurs",
    "Amateurs",
    "Hackers",
    "White hat attackers",
    "Black hat attackers",
    "Gray hat attackers",
    "Gray hat hackers",
    "Gray hat hackers",
    "Organized Hackers",
    "Cybercriminals",
    "Hacktivists",
    "State-sponsored attackers",
    "State-sponsored attackers",
    "State-sponsored attackers",
    "Internal threats",
    "White hat hackers",
    "White hat hackers",
    "Grey hat hackers",
    "Grey hat hackers",
    "Cyberspace",
    "Cyberwarfare",
    "Stuxnet",
    "Stuxnet",
    "Stuxnet",
    "Stuxnet",
    "Stuxnet",
    "Cyberwarfare",
    "Security Vulnerabilities",
    "Exploit",
    "Attack",
    "Software Vulnerabilities",
    "SYNful Knock",
    "SYNful Knock",
    "SYNful Knock",
    "Project Zero",
    "Hardware vulnerabilities",
    "Rowhammer",
    "Rowhammer",
    "Rowhammer",
    "Hardware vulnerabilities",
    "True",
    "Buffer overflow",
    "Buffer",
    "Buffer overflow",
    "Non-validated input",
    "Non-validated input",
    "Race conditions",
    "Race conditions", #bloop
    "Weaknesses in security practices",
    "Weaknesses in security practices",
    "Access control",
    "True",
    "Access control problems",
    "Buffer Overflow",
    "Malicious",
    "Software",
    "Malware",
    "Spyware",
    "Spyware",
    "True",
    "True",
    "Adware",
    "True",
    "Bot",
    "Botnets",
    "Ransomware",
    "Ransomware",
    "Ransomware",
    "Scareware",
    "Scareware",
    "Scareware",
    "Rootkit",
    "Rootkit",
    "Rootkit",
    "True",
    "Virus",
    "Virus",
    "Virus",
    "Trojan horse",
    "Trojan horse",
    "Trojan horse",
    "Worms",
    "Worms",
    "Worms",
    "Code Red",
    "Man in the Middle",
    "Man in the Middle",
    "Man in the Mobile",
    "Man in the Mobile",
    "ZeuS",
    "Social Engineering",
    "Social engineers",
    "Pretexting",
    "Pretexting",
    "Tailgating",
    "Quid pro quo",
    "Something for Something",
    "Something for Something",
    "Wi-Fi password cracking ",
    "Social Engineering",
    "Brute-force attacks",
    "Network sniffing",
    "Phishing",
    "Spear Phishing",
    "Spear Phishing",
    "whois",
    "nmap",
    "Advanced Persistent Threats",
    "Advanced Persistent Threats",
    "Advanced Persistent Threats",
    "Denial of Service",
    "Overwhelming Quantity of Traffic",
    "Overwhelming Quantity of Traffic",
    "Maliciously Formatted Packets",
    "Maliciously Formatted Packets",
    "Denial of Service",
    "Denial of Service",
    "Distributed Denial of Service Attack",
    "Botnet",
    "Zombies",
    "Handler systems",
    "Search Engine Optimization",
    "Search Engine Optimization",
    "Search Engine Optimization Poisoning",
    "Search Engine Optimization Poisoning",
    "Blended attacks",
    "Blended attacks",
    "Computing devices",
    "Shodan",
    "Service Set Identifier",
    "Key Reinstallation Attacks",
    "Eavesdropping",
    "Encryption",
    "True",
    "Encryption",
    "Encrypting File System",
    "Network Attached Storage",
    "Amazon Web Services",
    "SDelete",
    "Shred",
    "Secure Empty Trash",
    "Personal Identification Number",
    "Physical Object",
    "Biometric scan",
    "Open Authorization",
    "Open Authorization",
    "Open Authorization",
    "InPrivate",
    "Incognito",
    "Private tab or Private window",
    "Private browsing",
    "Secure Sockets Layer",
]


quez3 = [
    "are computer algorithms that use data to make estimations (educated guesses) or decisions.",
    "When normal computer software needs to be improved, people ______ it"
    "In the Boots That Fit Scenario, you own a shop that sells _________ for avalanche-rescue dogs",
    "In the BTF Scenario, you own a shop that sells harnesses for ____________",
    "A machine learning algorithm uses _____ to get better at a specific task",
    "A ____________ uses data to get better at a specific task",
    "Customers all seem to pick the correct harness sizes but are constantly ordering doggy ______ that are the wrong size. ",
    " you could approximate which doggy boots are the correct size, depending on the ______ chosen",
    " is the core component of machine learning, and ultimately what we are trying to build.",
    " might estimate how old a person is from a photo, predict what you might like to see on social media, or decide where a robotic arm should move to.",
    "machine learning models are shaped by _________",
    "models learn from?",
    "Note that harness size and dog boot size are data; they are not part of the model. ",
    "What is our input in BTF?"
    "What is our output in BTF?",
    "are discovered during training",
    " are not selected by the human designer",
    " Instead, parameter values are set to an initial guess, and then adjusted during an automated learning process called",
    "As you can see, we have the sizes of boots and harnesses for _____ avalanche dogs.",
    "We're just getting started, so we will start with a very simple model called ______. This is just a straight line",
    "OLS means?",
    "OLS is just a straight line, sometimes called?",
    "what do we import for ols?",
    "forumla for model thingy?",
    "formula for BTF?",
    "OLS model assignment thingy?",
    "OLS models have two parameters, what are they? ",
    "We need to train (_______) our model to find these values (parameters) so that the model can reliably estimate dogs' boot size based on their harness size.",
    "The goal of _______ is to improve a model so that it can make high-quality estimations or predictions. ",
    "Models don\'t train themselves, they're trained using data plus two pieces of code: the _________, and the optimizer.",
    "Models don\'t train themselves, they're trained using data plus two pieces of code: the objective function, and the ___________.",
    " is what we want to the model to be able to do",
    "So that a computer can understand our objective, we need to provide our goal as code snippet called an?",
    "they judge whether the model is doing a good job (estimating boot size well) or bad job (estimating boot size badly).",
    "refers to the information that we provide the model with",
    "data is also known as?"
    " also refers to information that the objective function might need",
    "During training, the model makes a prediction, and the _________ calculates how well it performed",
    "The _______ is code that then changes the model's parameters so the model will do a better job next time.",
    "The optimizer is code that then changes the model's ________ so the model will do a better job next time.",
    "dataset = pandas._________('doggy-boot-harness.csv')",
    "_____ dataset[\"sex\"] to delete row sex?",
    "________ a model means providing inputs and receiving an estimation or prediction.",
    "_______ a model is the process of improving how well a model works",
    "requires that we use the model, as well as the objective function and optimizer, in a special loop",
    "Usually, we only train a model how many times?.",
    "When we use our model, we only need the column(s) of data that the model accepts as input. These columns are called",
    "During training, the objective function usually needs to know both the model's output and what the correct answer was. These are called",
    "import _______ ______.dump(model,model_filename)",
    "joblib._____(model, model_filename)",
    "3 algorithms for Clustering?",
    "2 algorithms for Classifcation",
    "In the Elk Farm Case Scenario, what is the Feature?",
    "In the Elk Farm Case Scenaio, what is the Label?",
    "What is the angle of the line",
    "What moves the line up or down",

]

answers3 = [
    "Machine learning models",
    "edit",
    "harnesses",
    "avalanche-rescue dogs",
    "data",
    "machine learning algorithm",
    "boots",
    "harness",
    "Model",
    "Model",
    "Data",
    "experience",
    "true",
    "harness size",
    "dog boot size",
    "Parameters",
    "Parameter values",
    "training",
    "50",
    "OLS",
    "Ordinary Least Squares",
    "Trendline",
    "statsmodels.formula.api as smf",
    "formula = label ~ (is explained by) feature",
    "formula = boot_size ~ harness_size",
    "model = smf.ols(formula = formula, data = dataset)",
    "Slope, Offset",
    "fit",
    "training",
    "objective function",
    "optimizer",
    "objective",
    "objective function",
    "Objective functions",
    "data",
    "inputs",
    "data",
    "objective function",
    "optimizer",
    "parameters",
    "read_csv",
    "del",
    "Using",
    "training",
    "training",
    "once",
    "features",
    "labels",
    "joblib",
    "dump",
    "K-NN, K-Means, Hierarchical",
    "Apriori, FP-Growth",
    "Date",
    "Daily Temperature",
    "Slope",
    "Intercept",
]

#for item in answers3:
#    f = open("ans3.txt", "a")
#    f.write(f"{item}\n")
#    f.close()
